# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - octave
      - liboctave-dev

brew_packages:
  - octave

r_packages:
  - Rcpp
  - testthat
